### ISSUE TITLE
GTFS expired since 2016-07-31

### ISSUE THREAD

**Issue by LeoFrachet** [General-Transit-Feed-Specification/jta-fl-us#1]
**Summary** 

GTFS expired since 2016-07-31.

**Observed behavior** 

No direct link from the agency website, but a few GTFS aggregators have GTFSs from 2014 to 2016, but no update since March 2016:

Carl Weckenmann used to be the one posting it on GTFS Data Exchange.

**Actions taken** 

Email sent.

**Source URLs** 

- TransitFeeds: https://transitfeeds.com/p/jacksonville-transportation-authority/331
- GTFS Data Exchange: http://www.gtfs-data-exchange.com/agency/jacksonville-transportation-authority/

**Comment by barbeau** [comment]
This is what JTA emailed me as what they are publicly sharing.  They apparently updating their website to get a public URL going again - currently it's not posted, they are manually uploading to Google:
[Dec2016 - Trip Planners 1209.zip](https://github.com/General-Transit-Feed-Specification/jta-fl-us/files/661618/Dec2016.-.Trip.Planners.1209.zip)

**Comment by LeoFrachet** [comment]
New URL: http://www.jtafla.com/umbraco/surface/schedulesgtfs/index

**Comment by barbeau** [comment]
I submitted change to TransitFeeds.com:
https://github.com/TransitFeeds/TransitFeeds-Public/issues/211

I also just submitted JTA to Transit.land as well - they aren't listed there yet.

**Comment by barbeau** [comment]
Broken again, looks like it's moved to:
https://schedules.jtafla.com/schedulesgtfs/download

For future reference, the page that lists the link is at:
http://www.jtafla.com/schedules/
